### ISSUE TITLE
Visual Paradigm listed as supported but not available in list

### ISSUE THREAD

**Issue by myspivey** [jhipster/jhipster-uml#10]
When running jhipster-uml, Visual Paradigm is not provided as an available editor. When attempting to load UML using any of the three options, following error is presented.

/usr/local/lib/node_modules/jhipster-uml/lib/editors/genmymodel_parser.js:20
    this.root.packagedElement.forEach(function(element, index) {
                             ^
TypeError: Cannot read property 'forEach' of undefined
    at BaseConstructor.exports.GenMyModelParser.parser.AbstractParser.extend.findElements (/usr/local/lib/node_modules/jhipster-uml/lib/editors/genmymodel_parser.js:20:30)
    at BaseConstructor.exports.GenMyModelParser.parser.AbstractParser.extend.parse [as parse] (/usr/local/lib/node_modules/jhipster-uml/lib/editors/genmymodel_parser.js:11:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/jhipster-uml/jhipster-uml.js:37:8)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by myspivey** [comment]
Sorry did not see the latest release. Updated and now this works. Thanks!

**Comment by CarlKlagba** [comment]
Nice to hear that. Don't hesitate to give us feedbacks !

**Comment by jdhankins** [comment]
I have the latest version (1.5.1) of jhipster-uml and am still getting this error.  I am using version 12.1 of Visual Paradigm and generating xmi for a single entity with two columns as a test.  It seems like the VP parser is expecting the packagedElement element to exist off of the root, when it is actually a child of the uml:model/xmi:Extenion/vpumlChildModels xpath (at least in my xmi/uml output). 

Link to my uml: 
http://1drv.ms/1iK7PHe

Partial stack trace from running jhipster-uml test-jhipster.uml from the root of my jhipster project:
Cannot read property 'forEach' of undefined
TypeError: Cannot read property 'forEach' of undefined
    at VisualParadigmParser.findElements (/usr/local/lib/node_modules/jhipster-uml/lib/editors/visualparadigm_parser.js:31:28)
    at VisualParadigmParser.parse (/usr/local/lib/node_modules/jhipster-uml/lib/editors/visualparadigm_parser.js:19:8)

Please let me know if I'm doing something wrong on my end.
