### ISSUE TITLE
Issue when start - Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by lukasw44** [jhipster/jhipster-uml#102]
Hi

When i run project there is error:
my npm version:
3.3.12
node version:
v5.3.0
I want to generate class from visual paradigm but as you see there is some problem

Error:

Cannot read property 'forEach' of undefined
TypeError: Cannot read property 'forEach' of undefined
    at VisualParadigmParser.findElements (/home/lukasz/local/lib/node_modules/jhipster-uml/lib/editors/visualparadigm_parser.js:35:28)
    at VisualParadigmParser.parse (/home/lukasz/local/lib/node_modules/jhipster-uml/lib/editors/visualparadigm_parser.js:24:8)
    at Object.<anonymous> (/home/lukasz/local/lib/node_modules/jhipster-uml/jhipster-uml.js:82:27)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3

**Comment by lukasw44** [comment]
Hi 

When i run project there is error: 
my npm version: 
3.3.12
node version: 
v5.3.0
I want to generate class from visual paradigm but as you see there is some problem 

Error: 

```
Cannot read property 'forEach' of undefined
TypeError: Cannot read property 'forEach' of undefined
    at VisualParadigmParser.findElements (/home/lukasz/local/lib/node_modules/jhipster-uml/lib/editors/visualparadigm_parser.js:35:28)
    at VisualParadigmParser.parse (/home/lukasz/local/lib/node_modules/jhipster-uml/lib/editors/visualparadigm_parser.js:24:8)
    at Object.<anonymous> (/home/lukasz/local/lib/node_modules/jhipster-uml/jhipster-uml.js:82:27)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
```

**Comment by MathieuAA** [comment]
Helo, can you copy/paste your XMI file? or if the file contains sensitive information, send it by mail.
