### ISSUE TITLE
The validation 'minlength' isn't supported for the type 'Integer'. Error

### ISSUE THREAD

**Issue by mayurbais** [jhipster/jhipster-uml#112]
with the new branch,  new_parsed_data I am getting this error:(which was working earlier)

    The validation 'minlength' isn't supported for the type 'Integer'.
    Error
    at Object.<anonymous> (C:\Users\arjun\AppData\Roaming\npm\node_modules\jhipster-uml\lib\exceptions\wrong_validation_exception.js:7:38)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\arjun\AppData\Roaming\npm\node_modules\jhipster-uml\lib\editors\modelio_parser.js:10:32)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

**Comment by MathieuAA** [comment]
It's normal!! this branch doesn't even pass the tests! A lot of things don't work yet.

**Comment by mayurbais** [comment]
so, its not ready for use. we can use the fix for https://github.com/jhipster/jhipster-uml/issues/110
after this branch is merge to master?

**Comment by MathieuAA** [comment]
Yes. This branch is the right way to go but it takes quite a long time to upgrade each parser and I can't "release" a parser as soon as it is upgraded...

**Comment by mayurbais** [comment]
okay :)

**Comment by MathieuAA** [comment]
Oh and by the way, `minlength` isn't supported as a constraint in JHipster. That's why you got this message.

**Comment by mayurbais** [comment]
then why was it working just before the update to this branch, and 
I tried using     "minLength" first, it complained, so It tried     "minlength"

**Comment by MathieuAA** [comment]
Like I said, this branch is unstable. It may have worked at a time because of a bug. And because it's unstable, you can't rely on it. We expect users either to use a released version, or the master branch. The others are here for us, until we merge them into master.
