### ISSUE TITLE
Cannot process Modelio XMI from reverse-engineered MySQL schema

### ISSUE THREAD

**Issue by bojanraic** [jhipster/jhipster-uml#155]
### The issue
Using Modelio SD 3.4.1, I reverse engineered sample Employees MySQL schema and exported an XMI with OMG 2.4.1 compatibility. 
jhipster-uml fails with the following output: 

C:\Users\Developer\Desktop\hipapp>jhipster-uml ..\employees_mysql-5.7.11_modelio_3.4.1_omg-2.4.1.xmi
Parser detected: MODELIO.

Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at null.<anonymous> (C:\Users\Developer\AppData\Roaming\npm\node_modules\jhipster-uml\lib\editors\modelio_parser.js:253:97)
    at Array.forEach (native)
    at ModelioParser.fillConstraints (C:\Users\Developer\AppData\Roaming\npm\node_modules\jhipster-uml\lib\editors\modelio_parser.js:246:34)
    at ModelioParser.parse (C:\Users\Developer\AppData\Roaming\npm\node_modules\jhipster-uml\lib\editors\modelio_parser.js:31:8)
    at Object.<anonymous> (C:\Users\Developer\AppData\Roaming\npm\node_modules\jhipster-uml\jhipster-uml.js:94:27)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)

### Steps to reproduce

- Import sample employees schema into MySQL from [here](https://github.com/datacharmer/test_db/blob/master/employees.sql)
- Create a new Modelio SQL Project
- Reverse engineer all tables in employees schema
- Right-click on the resulting Modelio package -> XMI -> Export, choose file path and select OMG 2.4.1 compatibility
- From within a jhipster app folder, run jhipster-uml on the resulting XMI file

### The XMI or JDL file

[employees_mysql-5.7.11_modelio_3.4.1_omg-2.4.1.xmi.txt](https://github.com/jhipster/jhipster-uml/files/160106/employees_mysql-5.7.11_modelio_3.4.1_omg-2.4.1.xmi.txt)

### Versions

JHipster: 2.27.0

JHipster UML: 1.6.1

### Other Versions

OS: Windows 7 x64
MySQL: 5.7.11 x64
Modelio: SD 3.4.1
NodeJS: 5.6.0
NPM: 3.6.0

**Comment by MathieuAA** [comment]
Hi, it's absolutely "normal" as the result of a database content's dump is unexpected (the types are different, even the relationships). We don't support this kind of dumped XMI data, and we probably won't.
What you probably need is some kind of reverse-engineering tool to properly dump the data to something we can read.
