### ISSUE TITLE
Accept .jdl file extension and not only .jh

### ISSUE THREAD

**Issue by andidev** [jhipster/jhipster-uml#159]
### The issue
Its strange that the jdl file passed to jhipster uml needs to named .jh. Naming it .jdl which for me is more logical since we always speak of it as the jdl file should also be okey. Maybe the file extensions should not even be restricted at all? Is there a reason for this restriction? I dont know how many times I named it  .jdl instead of .jh and got this nasty stack trace

```bash
$ jhipster-uml test.jdl 
An error has occurred:
	TypeError
Error message:
	Cannot read property 'hasOwnProperty' of undefined
Stack trace:
TypeError: Cannot read property 'hasOwnProperty' of undefined
    at /Users/anders/Workspace/jhipster-uml/lib/editors/parser_factory.js:88:15
    at Parser.<anonymous> (/Users/anders/Workspace/jhipster-uml/node_modules/xml2js/lib/xml2js.js:488:18)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Object.onerror (/Users/anders/Workspace/jhipster-uml/node_modules/xml2js/lib/xml2js.js:309:26)
    at emit (/Users/anders/Workspace/jhipster-uml/node_modules/sax/lib/sax.js:639:35)
    at error (/Users/anders/Workspace/jhipster-uml/node_modules/sax/lib/sax.js:668:5)
    at strictFail (/Users/anders/Workspace/jhipster-uml/node_modules/sax/lib/sax.js:692:7)
    at beginWhiteSpace (/Users/anders/Workspace/jhipster-uml/node_modules/sax/lib/sax.js:965:7)
    at Object.write (/Users/anders/Workspace/jhipster-uml/node_modules/sax/lib/sax.js:1006:11)
```

or maybe the stacktrace should be replaced with a file extension check?

**Comment by MathieuAA** [comment]
Frankly, I don't know why we still don't allow this extension. I'll do it ASAP (tonight)!

**Comment by CarlKlagba** [comment]
It was because the .jdl already existe but that's for some obscure database. Shouldn't be a problem.

**Comment by MathieuAA** [comment]
It's finally done!
