### ISSUE TITLE
Using VP, tried minlength on Integer with error

### ISSUE THREAD

**Issue by myspivey** [jhipster/jhipster-uml#16]
The validation 'minlength' isn't supported for the type 'Integer', exiting now.
Error
    at Object.<anonymous> (/usr/local/lib/node_modules/jhipster-uml/lib/editors/visualparadigm_parser.js:359:38)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/jhipster-uml/lib/editors/editors.js:6:29)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
Lightning:commission-entry Lightning$

**Comment by CarlKlagba** [comment]
The constraints on the 'Integer' size are 'min' and 'max'. We made a mistake in our documentation and in the entity generation code. We will fix it in the next release.

**Comment by MathieuAA** [comment]
I just tested it with Modelio and Visual Paradigm, and no exceptio was thrown at me...
As @CarlKlagba said, you have to use `min` and `max` with decimal types (integer, bigdecimal and long).
There is an issue however with the wiki, and a fix has been proposed.

**Comment by CarlKlagba** [comment]
@MathieuAA You can use "min" and "max" and there will be be no exception during the JH-UML generation  but the field wont have the property fieldValidateRulesMax.

cf the function setValidationsOfField in EntityGenerator:

if(validationName === "maxlength"){
   field.fieldValidateRulesMaxlength = this.fields[fieldId].validations[j];
}else if(validationName === "minlength"){
   field.fieldValidateRulesMinlength = this.fields[fieldId].validations[j];
}

I am making a fix.

**Comment by MathieuAA** [comment]
Ah ok! My bad.

**Comment by myspivey** [comment]
Thanks CarlKlagba! When do we think we can get that released? Thanks!

**Comment by MathieuAA** [comment]
I'll release that ASAP =)
