### ISSUE TITLE
Exception when invoked with optional parameters

### ISSUE THREAD

**Issue by alcidesmorales** [jhipster/jhipster-uml#161]
### The issue

Calling the jhipster-uml command with optional parameters raise an exception.

I think the problem may be in the function initParserFactoryArgs, at line 131 parser got confused and assume that there are more input files. Just an idea.

```
function initParserFactoryArgs(type) {
  var parserFactoryArgs = { databaseType: type };
  if (process.argv.length === 3) {
    parserFactoryArgs.file = process.argv[2];
  } else {
    parserFactoryArgs.files = process.argv.slice(2);
  }
  return parserFactoryArgs;
}

```

---
#### The stacktrace

An error has occurred:
        WrongPassedArgumentException
Error message:
        Only one XMI file can be passed, and mixing JDL and XMI files is not allowed.
Stack trace:
Error
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\jhipster-uml\lib\exceptions\wrong_passed_argument_exception.js:7:42)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\jhipster-uml\lib\editors\parser_factory.js:13:36)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

---

### Steps to reproduce

jhipster-uml  models\model.xmi -service

### Versions

| JHipster           | JHipster UML           |
| ------------------ | ---------------------- |
| 2.27.2	| 1.6.3 |

**Comment by MathieuAA** [comment]
I've reproduced the issue, I'll fix it tomorrow. Sorry for the inconvenience!
