### ISSUE TITLE
The jhipster-uml cmd tool reads maxbytes as maxlength for ImageBlob and throws ValidationExc.

### ISSUE THREAD

**Issue by WhyINeedToFillUsername** [jhipster/jhipster-uml#185]
### The issue
When using jhipster-uml command-line tool for creating entities from JDL file, it throws an `WrongValidationException`, because it incorrectly reads `maxbytes` validation instruction for `ImageBlob` as `maxlength`, which is not allowed at `ImageBlob`.

The `maxbytes` for `ImageBlob` should be supported according to the [documentation](https://jhipster.github.io/jhipster-uml/) (Annexes).

---
#### The stacktrace
```
c:\dev\projects\projectName>jhipster-uml entities-jdl.jh -db sql
An error has occurred:
        WrongValidationException
Error message:
        The validation 'maxlength' isn't supported for the type 'ImageBlob'.
Stack trace:
Error
    at Object.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\jhipster-uml\lib\exceptions\wrong_validation_exception.js:7:38)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\jhipster-uml\lib\editors\modelio_parser.js:10:32)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
```

---
### Steps to reproduce
Create a file using JDL with entity which has an ImageBlob field with maxbytes validation, pass this file as argument for jhipster-uml.

---
### The XMI or JDL file
```
entity EntityName{
	avatar ImageBlob maxbytes(100000)
}
```
---
### Versions

| JHipster           | JHipster UML           |
| ------------------ | ---------------------- |
| `3.1.0` |    `1.6.5.`   |

**Comment by MathieuAA** [comment]
Hi, it was fixed in the 14th issue, [here](https://github.com/jhipster/jhipster-domain-language/issues/14). But not yet released. Everything related to the JDL isn't here anymore.

**Comment by WhyINeedToFillUsername** [comment]
Sry, thought it's an issue of the jhipster-uml. Will search more thoroughly not to report duplicated issues next time :)

**Comment by MathieuAA** [comment]
Don't worry, it's better to ask anyway.
