### ISSUE TITLE
installation error on linux mint 18 64bit

### ISSUE THREAD

**Issue by sohibegit** [jhipster/jhipster-uml#200]
### The issue

error installing jhipster-uml on

Linux Mint 18 64Bit 4.4.0-31-generic #50-Ubuntu SMP 
npm version 3.10.5
---
#### The stacktrace

```
sohibe@sohibe-Z87-D3HP ~ $ npm install -g jhipster-uml
/home/sohibe/.nvm/versions/node/v6.3.0/bin/jhipster-uml -> /home/sohibe/.nvm/versions/node/v6.3.0/lib/node_modules/jhipster-uml/jhipster-uml.js

> deasync@0.1.4 install /home/sohibe/.nvm/versions/node/v6.3.0/lib/node_modules/jhipster-uml/node_modules/deasync
> node ./build.js

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/home/sohibe/.nvm/versions/node/v6.3.0/lib/node_modules/jhipster-uml/node_modules/deasync/build'
  CXX(target) Release/obj.target/deasync/src/deasync.o
make: g++: Command not found
deasync.target.mk:94: recipe for target 'Release/obj.target/deasync/src/deasync.o' failed
make: *** [Release/obj.target/deasync/src/deasync.o] Error 127
make: Leaving directory '/home/sohibe/.nvm/versions/node/v6.3.0/lib/node_modules/jhipster-uml/node_modules/deasync/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/sohibe/.nvm/versions/node/v6.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.4.0-31-generic
gyp ERR! command "/home/sohibe/.nvm/versions/node/v6.3.0/bin/node" "/home/sohibe/.nvm/versions/node/v6.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/sohibe/.nvm/versions/node/v6.3.0/lib/node_modules/jhipster-uml/node_modules/deasync
gyp ERR! node -v v6.3.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
Build failed
/home/sohibe/.nvm/versions/node/v6.3.0/lib
└── (empty)

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/home/sohibe/.nvm/versions/node/v6.3.0/bin/node" "/home/sohibe/.nvm/versions/node/v6.3.0/bin/npm" "install" "-g" "jhipster-uml"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! deasync@0.1.4 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the deasync@0.1.4 install script 'node ./build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the deasync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs deasync
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls deasync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sohibe/npm-debug.log
npm ERR! code 1
```

---

### Steps to reproduce

npm install -g jhipster-uml 

---

### The XMI or JDL file

---

### Versions

| JHipster           | JHipster UML           |
| ------------------ | ---------------------- |
| `3.5.1` |    `jhipster-uml -v`   |

[npm-debug.log.txt](https://github.com/jhipster/jhipster-uml/files/380496/npm-debug.log.txt)

**Comment by jdubois** [comment]
- Please write a correct title
- What's important is your Node version -> we usually only support LTS release. I'd be surprised it doesn't work with Node 6.x, but it can happen as you're on an unstable version. Can you try again with Node 4.x ?

**Comment by MathieuAA** [comment]
What Julien said, and check that you have g++ installed (`make: g++: Command not found`).

**Comment by sohibegit** [comment]
It worked after I installed build-essential and g++ 
Thanks for help

**Comment by MathieuAA** [comment]
You're welcome!
