### ISSUE TITLE
JHipster UML  2.0.0 Cannot read property 'hasOwnProperty' of undefined JD file

### ISSUE THREAD

**Issue by sohibegit** [jhipster/jhipster-uml#210]
### The issue

can't generate entities using JD file

---
#### The stacktrace

```
 jhipster-uml jhipster-jdl.jh -f
An error has occurred:
	TypeError
Error message:
	Cannot read property 'hasOwnProperty' of undefined
Stack trace:
TypeError: Cannot read property 'hasOwnProperty' of undefined
    at /home/sohibe/.nvm/versions/node/v6.5.0/lib/node_modules/jhipster-uml/lib/editors/parser_factory.js:67:15
    at Parser.<anonymous> (/home/sohibe/.nvm/versions/node/v6.5.0/lib/node_modules/jhipster-uml/node_modules/xml2js/lib/xml2js.js:493:18)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Object.onerror (/home/sohibe/.nvm/versions/node/v6.5.0/lib/node_modules/jhipster-uml/node_modules/xml2js/lib/xml2js.js:311:26)
    at emit (/home/sohibe/.nvm/versions/node/v6.5.0/lib/node_modules/jhipster-uml/node_modules/sax/lib/sax.js:640:35)
    at error (/home/sohibe/.nvm/versions/node/v6.5.0/lib/node_modules/jhipster-uml/node_modules/sax/lib/sax.js:669:5)
    at strictFail (/home/sohibe/.nvm/versions/node/v6.5.0/lib/node_modules/jhipster-uml/node_modules/sax/lib/sax.js:693:7)
    at beginWhiteSpace (/home/sohibe/.nvm/versions/node/v6.5.0/lib/node_modules/jhipster-uml/node_modules/sax/lib/sax.js:967:7)
    at Object.write (/home/sohibe/.nvm/versions/node/v6.5.0/lib/node_modules/jhipster-uml/node_modules/sax/lib/sax.js:1019:11)

```

---

### Steps to reproduce

 jhipster-uml jhipster-jdl.jh -f

---

### The XMI or JDL file

entity Region {
	regionName String
}

entity Country {
	countryName String
}

entity Location {
	streetAddress String,
	postalCode String,
	city String,
	stateProvince String
}

entity Department {
	departmentName String required
}

entity Task {
	title String,
	description String
}

entity Employee {
	firstName String,
	lastName String,
	email String,
	phoneNumber String,
	hireDate ZonedDateTime,
	salary Long,
	commissionPct Long
}

entity Job {
	jobTitle String,
	minSalary Long,
	maxSalary Long
}

entity JobHistory {
	startDate ZonedDateTime,
	endDate ZonedDateTime,
	language Language
}

enum Language {
    FRENCH, ENGLISH, SPANISH
}

relationship OneToOne {
	Country{region} to Region
}

relationship OneToOne {
	Location{country} to Country
}

relationship OneToOne {
	Department{location} to Location
}

relationship ManyToMany {
	Job{task(title)} to Task{job}
}

relationship OneToMany {
	Employee{job} to Job,
	Department{employee} to
	Employee
}

relationship ManyToOne {
	Employee{manager} to Employee
}

relationship OneToOne {
	JobHistory{job} to Job,
	JobHistory{department} to Department,
	JobHistory{employee} to Employee
}
---

### Versions

| JHipster           | JHipster UML           |
| ------------------ | ---------------------- |
| `JHipster 3.9.0` |    `JHipster UML is 2.0.0`   |

**Comment by MathieuAA** [comment]
Hi, it's normal! JUML doesn't deal with JDL files any more, you have to use the subgen now (with `yo jhipster:import-jdl`).
