### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by somewhereMrli** [jhipster/jhipster-uml#214]
PS F:\jhipster\app> jhipster-uml project1.xmi
Parser detected: MODELIO.

An error has occurred:
        WrongTypeException
Error message:
        The type 'ELong' isn't supported by JHipster.

**Comment by MathieuAA** [comment]
Yes, you must be using the wrong UML implementation. Carefully read the doc [here](https://jhipster.github.io/jhipster-uml/#modelioexample) about how exporting is done.

**Comment by somewhereMrli** [comment]
https://github.com/jhipster/jhipster-uml/blob/master/test/xmi/visualparadigm.uml  404   

I use Visual Paradigm for UML 10.0  get uml ,but

jhipster-uml testAlbedo.xmi.uml
? Please choose between the available editors: (Press <space> to select)
An error has occurred:
        TypeError
Error message:
        Cannot read property 'parse' of undefined
Stack trace:
TypeError: Cannot read property 'parse' of undefined
    at Object.<anonymous> (E:\nodejs\node_global\node_modules\jhipster-uml\lib\jhipsteruml.js:54:24)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\nodejs\node_global\node_modules\jhipster-uml\jhipster-uml.js:7:3)
    at Module._compile (module.js:541:32)

**Comment by MathieuAA** [comment]
Yes, Visual Paradigm is no longer supported. Please open a new issue next time, these two are different.

**Comment by somewhereMrli** [comment]
ok, Thanks!
