### ISSUE TITLE
Error: Cannot read property 'relationships' of undefined 

### ISSUE THREAD

**Issue by yvillazon** [jhipster/jhipster-uml#256]
### The issue
Cannot read property 'relationships' of undefined trying parse JDL file.

---
### The command
yo jhipster:import-jdl jhipster-jdl.jh

---
#### The stacktrace

The jdl is being parsed.
Warning:  An Entity name 'User' was used: 'User' is an entity created by default by JHipster. All relationships toward it will be kept but any attributes and relationships from it will be disregarded.
TypeError: Cannot read property 'relationships' of undefined
    at setSourceAssociationsForClass (/home/yoandypv/Desarrollo/Java/pruebas/jhipster-test/guias/node_modules/jhipster-core/lib/parser/entity_parser.js:287:46)
    at setRelationshipOfEntity (/home/yoandypv/Desarrollo/Java/pruebas/jhipster-test/guias/node_modules/jhipster-core/lib/parser/entity_parser.js:246:3)
    at fillEntities (/home/yoandypv/Desarrollo/Java/pruebas/jhipster-test/guias/node_modules/jhipster-core/lib/parser/entity_parser.js:143:7)
    at Object.parse [as convertToJHipsterJSON] (/home/yoandypv/Desarrollo/Java/pruebas/jhipster-test/guias/node_modules/jhipster-core/lib/parser/entity_parser.js:42:3)
    at constructor.parseJDL (/home/yoandypv/Desarrollo/Java/pruebas/jhipster-test/guias/node_modules/generator-jhipster/generators/import-jdl/index.js:78:42)
    at Object.<anonymous> (/home/yoandypv/Desarrollo/Java/pruebas/jhipster-test/guias/node_modules/yeoman-generator/lib/index.js:417:23)
    at /home/yoandypv/Desarrollo/Java/pruebas/jhipster-test/guias/node_modules/run-async/index.js:25:25
    at /home/yoandypv/Desarrollo/Java/pruebas/jhipster-test/guias/node_modules/run-async/index.js:24:19
    at /home/yoandypv/Desarrollo/Java/pruebas/jhipster-test/guias/node_modules/yeoman-generator/lib/index.js:418:9
    at runCallback (timers.js:637:20)
Error jhipster:import-jdl jhipster-jdl.jh 

ERROR! 
Error while parsing entities from JD

---

### Steps to reproduce

---

### The XMI file

entity Usuario {	
    userkind UsuarioKind required,
    birthday LocalDate, 
    mainpict ImageBlob,
    backgroundpict ImageBlob,
    brief String,
    facebook String, 
    twitter String,
    linkedin String,
    webpage String,
}

entity Post {
	weburl String, 
    image ImageBlob,
    text String, 
}

enum UsuarioKind {
  TOURIST, TOURIST_GUIDE
}

entity SpeakLanguages{
	languagename String,
    flagid String
}

entity Comment {
	title String,
	message String required, 
    likes Integer min(0)
}

entity Skill {
	name String required,
    description String,
}

relationship ManyToMany {
Usuario {friend} to Usuario
}

relationship OneToMany {
 Comment {usuario} to User
}

relationship OneToMany {
 Comment {message} to Post
}

relationship OneToMany {
Usuario {SpeakLanguages(languagename)} to SpeakLanguages
}

relationship OneToMany {
Usuario {Skill(name)} to Skill
}

relationship OneToOne {
	Usuario{user} to User{usuario}
}

paginate * with infinite-scroll

---

### Versions 

| JHipster            | JHipster UML           | Editor & version | 
| ------------------ | ---------------------- | ---------------- |
| `v4.5.6` |    `--`   |                  |

**Comment by MathieuAA** [comment]
Hi, first of all, you've submitted this to the wrong repo (it should be in the generator or JHipster Core).
I'll test it out...
