### ISSUE TITLE
How to modify existing entity generated with jhipster?

### ISSUE THREAD

**Issue by knavadiya** [jhipster/jhipster-uml#262]
I am using jhipster (jhipsterVersion -> 4.11.1), I have created Student entity through "yo jhipster:entity" student and add fields like rollNo,name,course. after that run gradlew commad to run application so far everything is working fine, entity is created successful with given proper field.

But after 1 days I required to add new field like collegeName and i ran "yo jhipster:entity student" command again and add one more field collegeName and to got message built successful but when i run gradlew command to run application I got error like Below

2017-12-28 15:19:33.969 ERROR 2484 --- [tapp-Executor-1] i.g.j.c.liquibase.AsyncSpringLiquibase   :
Liquibase could not start correctly, your database is NOT ready: Validation Failed:
     1 change sets check sum
          config/liquibase/changelog/20171228063150_added_entity_Student.xml::20171228063150-1::jhip
ster was: 7:1e76a424cb8d1fd8f33d27559cee9133 but is now: 7:a69d676fb7b3d1b37c22d109340b7c2b

liquibase.exception.ValidationFailedException: Validation Failed:
     1 change sets check sum
          config/liquibase/changelog/20171228063150_added_entity_Student.xml::20171228063150-1::jhip
ster was: 7:1e76a424cb8d1fd8f33d27559cee9133 but is now: 7:a69d676fb7b3d1b37c22d109340b7c2b

        at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:266)
        at liquibase.Liquibase.update(Liquibase.java:210)
        at liquibase.Liquibase.update(Liquibase.java:192)
        at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:431)
        at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:388)

        at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java
:82)
        at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.lambda$afterPropertiesSet$0(Asyn
cSpringLiquibase.java:64)
        at io.github.jhipster.async.ExceptionHandlingAsyncTaskExecutor.lambda$createWrappedRunnable$
1(ExceptionHandlingAsyncTaskExecutor.java:66)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

2017-12-28 15:19:45.285  INFO 2484 --- [  restartedMain] com.quote.TestappApp                     :
Started TestappApp in 26.183 seconds (JVM running for 27.099)
2017-12-28 15:19:45.296  INFO 2484 --- [  restartedMain] com.quote.TestappApp                     :

If I add/remove fields and relationships to an existing entity through commands then should I generate change log by " gradlew liquibaseDiffChangelog " command and generated change log file to your src/main/resources/config/liquibase/master.xml file myself manually or All the task will completed automatically ?
--

**Comment by jdubois** [comment]
I'm sorry but this is the issue tracker - if you have general questions on using JHipster, please use StackOverflow with the "jhipster" tag.
