### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by yuniel-acosta** [jhipster/jhipster-uml#267]
### Modelio v3.8 introduces a bug when dealing with bidirectional Many-to-Many relationships (the error when JHipster UML parses the XMI is Cannot read property '0' of undefined)

In the official documentation of jhipster UML it is explained that there is a bug with Modelio 3.5.x in the generation of bidirectional Many-to-Many relationships and that it will be fixed for version 6. As it turns out, I am using version 3.8 and even persite the problem

```
jhipster-uml .\dallay.xmi

Parser detected: MODELIO.

An error has occurred:
        TypeError
Error message:
        Cannot read property '0' of undefined
Stack trace:
TypeError: Cannot read property '0' of undefined
    at addAssociation (C:\Users\Acosta\AppData\Local\Yarn\Data\global\node_modules\jhipster-uml\lib\editors\modelio_parser.js:161:38)
    at fillAssociations (C:\Users\Acosta\AppData\Local\Yarn\Data\global\node_modules\jhipster-uml\lib\editors\modelio_parser.js:155:5)
    at Object.parse (C:\Users\Acosta\AppData\Local\Yarn\Data\global\node_modules\jhipster-uml\lib\editors\modelio_parser.js:28:3)
    at Object.<anonymous> (C:\Users\Acosta\AppData\Local\Yarn\Data\global\node_modules\jhipster-uml\lib\jhipsteruml.js:54:25)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)

```

---

### Reproduce the error

This is the model
[image](https://ibb.co/VJZwJkG)
[xmi](https://drive.google.com/open?id=1DYwQocMld5vqr9YxUypDyNtjRZ1KM042)
---

### The XMI file

[image](https://ibb.co/VJZwJkG)
[xmi](https://drive.google.com/open?id=1DYwQocMld5vqr9YxUypDyNtjRZ1KM042)
---

### Versions 

| JHipster               | JHipster UML           | Editor & version |
| ------------------ | ---------------------- | ---------------- |
| `5.8.2`                  |    `2.0.3`   |    `Modelio 3.8`               |

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
The only workaround I found was to downgrade or upgrade to a more stable version. Can you do it?

**Comment by Yerikshu** [comment]
hey, i aslo meet this error, and my jhipster's version is 5.7.1, jhipster uml's version is 2.0.3, and modelio is 3.8.
this is my xmi
<?xml version="1.0" encoding="UTF-8"?><uml:Model xmlns:uml="http://schema.omg.org/spec/UML/2.2" xmlns:xmi="http://schema.omg.org/spec/XMI/2.1" xmi:version="2.1" xmi:id="_Cw3q8LNeEem9peYs6b868w" name="pingsec">
  <eAnnotations xmi:id="_Cw3q8bNeEem9peYs6b868w" source="Objing">
    <contents xmi:type="uml:Property" xmi:id="_Cw3q8rNeEem9peYs6b868w" name="exporterVersion">
      <defaultValue xmi:type="uml:LiteralString" xmi:id="_Cw3q87NeEem9peYs6b868w" value="3.0.0"/>
    </contents>
  </eAnnotations>
  <packagedElement xmi:type="uml:Class" xmi:id="_Cw3q9LNeEem9peYs6b868w" name="Piner">
    <ownedAttribute xmi:type="uml:Property" xmi:id="_Cw3q9bNeEem9peYs6b868w" name="course" visibility="public" type="_Cw3q-7NeEem9peYs6b868w" aggregation="shared" association="_Cw3q-rNeEem9peYs6b868w">
      <upperValue xmi:type="uml:LiteralUnlimitedNatural" xmi:id="_Cw3q9rNeEem9peYs6b868w" value="*"/>
    </ownedAttribute>
    <ownedAttribute xmi:type="uml:Property" xmi:id="_Cw3q97NeEem9peYs6b868w" name="name" visibility="public" isUnique="false">
      <type xmi:type="uml:PrimitiveType" href="http://schema.omg.org/spec/UML/2.2/uml.xml#String"/>
    </ownedAttribute>
    <ownedAttribute xmi:type="uml:Property" xmi:id="_Cw3q-LNeEem9peYs6b868w" name="pwd" visibility="public" isUnique="false">
      <type xmi:type="uml:PrimitiveType" href="http://schema.omg.org/spec/UML/2.2/uml.xml#String"/>
    </ownedAttribute>
    <ownedAttribute xmi:type="uml:Property" xmi:id="_Cw3q-bNeEem9peYs6b868w" name="studyTime" visibility="public" type="_Cw3rA7NeEem9peYs6b868w" isUnique="false"/>
  </packagedElement>
  <packagedElement xmi:type="uml:Association" xmi:id="_Cw3q-rNeEem9peYs6b868w" memberEnd="_Cw3q9bNeEem9peYs6b868w _Cw3q_LNeEem9peYs6b868w"/>
  <packagedElement xmi:type="uml:Class" xmi:id="_Cw3q-7NeEem9peYs6b868w" name="Course">
    <ownedAttribute xmi:type="uml:Property" xmi:id="_Cw3q_LNeEem9peYs6b868w" name="piner" visibility="public" type="_Cw3q9LNeEem9peYs6b868w" association="_Cw3q-rNeEem9peYs6b868w">
      <upperValue xmi:type="uml:LiteralUnlimitedNatural" xmi:id="_Cw3q_bNeEem9peYs6b868w" value="*"/>
    </ownedAttribute>
    <ownedAttribute xmi:type="uml:Property" xmi:id="_Cw3q_rNeEem9peYs6b868w" name="attribution" visibility="public" isUnique="false">
      <type xmi:type="uml:PrimitiveType" href="http://schema.omg.org/spec/UML/2.2/uml.xml#String"/>
    </ownedAttribute>
    <ownedAttribute xmi:type="uml:Property" xmi:id="_Cw3q_7NeEem9peYs6b868w" name="name" visibility="public" isUnique="false">
      <type xmi:type="uml:PrimitiveType" href="http://schema.omg.org/spec/UML/2.2/uml.xml#String"/>
    </ownedAttribute>
    <ownedAttribute xmi:type="uml:Property" xmi:id="_Cw3rALNeEem9peYs6b868w" name="description" visibility="public" isUnique="false">
      <type xmi:type="uml:PrimitiveType" href="http://schema.omg.org/spec/UML/2.2/uml.xml#String"/>
    </ownedAttribute>
    <ownedAttribute xmi:type="uml:Property" xmi:id="_Cw3rAbNeEem9peYs6b868w" name="statistic" visibility="public" type="_Cw3rA7NeEem9peYs6b868w" isUnique="false"/>
    <ownedAttribute xmi:type="uml:Property" xmi:id="_Cw3rArNeEem9peYs6b868w" name="studyLength" visibility="public" type="_Cw3rA7NeEem9peYs6b868w" isUnique="false"/>
  </packagedElement>
  <packagedElement xmi:type="uml:PrimitiveType" xmi:id="_Cw3rA7NeEem9peYs6b868w" name="long"/>
</uml:Model>
