### ISSUE TITLE
every attempt to generate fails with error

### ISSUE THREAD

**Issue by andyverbunt** [jhipster/jhipster-uml#50]
Even the most simple .jh file (e.g. the one with author/book from the documentation) doesn't work as expected. It fails with an error.

I must be doing something wrong??

```

entity Book{
  title String required,
  description String required minlength(5) maxlength(50),
  publicationDate LocalDate,
  price BigDecimal
}
entity Author{
  name String required,
  birthDate LocalDate
}
relationship OneToMany{
  Author{book} to Book{writer}
}

```

```

jhipster-uml book.jh 

```

```

Cannot read property 'classes' of undefined
TypeError: Cannot read property 'classes' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/jhipster-uml/jhipster-uml.js:72:27)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

```

**Comment by CarlKlagba** [comment]
Like for #51, it seems like we have a JDL issue. I will look at it when I have time.

**Comment by andyverbunt** [comment]
Do you have any idea what's wrong?
This is completely blocking :(

**Comment by CarlKlagba** [comment]
That's wierd, I can replicate on my setup.

**Comment by andyverbunt** [comment]
That's a good thing, no?

**Comment by CarlKlagba** [comment]
According to @MathieuAA,  this is a resolved issue on the master. Try to clone the repo and do a npm link. He will make a release soon.

**Comment by MathieuAA** [comment]
The fix has been released, sorry for the delay. Could you try it out?

**Comment by andyverbunt** [comment]
Hi Mathieu,

Seems like it's fixed now :)
Thanks very much!!

Unfortunately, I'm now facing another problem. I cannot reference the "predefined" User entity.
Should I open another issue for that? Or is there a trick I don't know about?

```
...
relationship OneToMany {
    User{photo} to Photo{owner}
}
...

```

```

Cannot read property 'User' of undefined
TypeError: Cannot read property 'User' of undefined
    at DSLParser.checkEntityDeclaration (/usr/local/lib/node_modules/jhipster-uml/lib/dsl/dsl_parser.js:172:93)
    at DSLParser.fillAssociations (/usr/local/lib/node_modules/jhipster-uml/lib/dsl/dsl_parser.js:50:10)
    at DSLParser.parse (/usr/local/lib/node_modules/jhipster-uml/lib/dsl/dsl_parser.js:26:8)
    at Object.<anonymous> (/usr/local/lib/node_modules/jhipster-uml/jhipster-uml.js:69:27)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)

```

**Comment by MathieuAA** [comment]
The tests didn't detect that... our bad. I'm going to fix it right away.

**Comment by MathieuAA** [comment]
I will close this thread tonight after testing the latest modifications, and make a patch release out of it.
