### ISSUE TITLE
release 1.4.0+ is not working anymore with my model from Modelio, release 1.3.2 works fine.

### ISSUE THREAD

**Issue by marcelinobadin** [jhipster/jhipster-uml#57]
Hi!
I'm using Modelio to model my entities and once I did the upgrade to **1.4.0 and higher** ones it is not working. The exception is:
```
Parser detected: MODELIO.

Object.keys called on non-object
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at askForClassesToPaginate (/Users/Marcelino/.nvm/versions/v0.12.4/lib/node_modules/jhipster-uml/jhipster-uml.js:200:12)
    at askForPagination (/Users/Marcelino/.nvm/versions/v0.12.4/lib/node_modules/jhipster-uml/jhipster-uml.js:169:15)
    at Object.<anonymous> (/Users/Marcelino/.nvm/versions/v0.12.4/lib/node_modules/jhipster-uml/jhipster-uml.js:83:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
```
Once a roll back to 1.3.2 it works fine.
If someone can help me and needs more information to help, just ask what you need.
Thank you.

**Comment by MathieuAA** [comment]
Try to pull from the latest version, from git.
I committed a fix last night from a pull request that may be related to your problem.

**Comment by marcelinobadin** [comment]
Cool! Thanks. It works now.

**Comment by MathieuAA** [comment]
I'm going to wait a bit before releasing the fix. I have a lot of things to add before making a release.
