### ISSUE TITLE
Invalid Type Exception with Modelio

### ISSUE THREAD

**Issue by outis10** [jhipster/jhipster-uml#8]
Hi, there, I try to use the app with this  basic model

![model](https://cloud.githubusercontent.com/assets/4823082/8167790/6f599d22-1355-11e5-80ec-fe9d2331e78f.png)

but when y ran the jhipster-uml it throws me the following error

λ jhipster-uml spyderfox.xmi
Parser detected: MODELIO.

C:\Users\narciso.parra\AppData\Roaming\npm\node_modules\jhipster-uml\lib\editors\modelio_parser.js:62
      throw new InvalidTypeException(
            ^
Error
    at Object.<anonymous> (C:\Users\narciso.parra\AppData\Roaming\npm\node_modules\jhipster-uml\lib\editors\modelio_parser.js:329:34)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\narciso.parra\AppData\Roaming\npm\node_modules\jhipster-uml\lib\editors\editors.js:3:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

Thanks in advance!

**Comment by MathieuAA** [comment]
Hi!

I may be wrong, but I doubt 'Date' (from the 'Credito' entity) exists for your database type. Date is only supported by JHipster for Cassandra. If you're using a SQL database, or a MongoDB one, the error is normal.

However, another issue is pointer by your proble:m the display of exceptions. We're currently trying to make it work as intended (Javascript doesn't make it easier for us), and help users see their mistakes, or --better, our mistakes.

I'm not closing this thread until the JHipster-UML fixes the exception problem.

I hope my answer helped you, thanks for using JHipster-UML!

**Comment by MathieuAA** [comment]
The exception problem is now fixed as of the last commit.

**Comment by outis10** [comment]
Ok, i see the correct error right now
    The type 'Date' isn't supported by JHipster, exiting now.
    Error...
and  I modify my model with LocalDate Class

![image](https://cloud.githubusercontent.com/assets/4823082/8170207/eed521bc-1363-11e5-8eab-8e6b0af21887.png)

And there is a new error message
The type 'EDate' isn't supported by JHipster, exiting now.
Error
    at Object.<anonymous> (C:\Users\narciso.parra\AppData\Roaming\npm\node_modules\jhipster-uml\lib\editors\modelio_parser.js:333:34)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\narciso.parra\AppData\Roaming\npm\node_modules\jhipster-uml\lib\editors\editors.js:3:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

I don´t know is this is for a bug or something wrong whit  the manner of i design the model

**Comment by MathieuAA** [comment]
You must have chosen the wrong date type. EDate could be the Ecore type. Something's wrong with your diagram. Try to export it to XMI and look for the EDate DataType or PrimitiveType.
If there's one, you have your error.

**Comment by outis10** [comment]
You are right. I fix my model and it run well. its awesome

And Again Thanks!

**Comment by MathieuAA** [comment]
Happy to help =)
