### ISSUE TITLE
The field 'name' does not possess any type, exiting now.

### ISSUE THREAD

**Issue by pr0t3us** [jhipster/jhipster-uml#9]
Exported a test xmi file from Modelio but can't make it work with jhipster-uml
![screenshot](https://cloud.githubusercontent.com/assets/1947850/8205147/9ed63676-14f6-11e5-950f-a5caeb3e583f.png)
I'm missing something?

**Comment by CarlKlagba** [comment]
Can you post the exact error message and also the faulty JSON?

**Comment by CarlKlagba** [comment]
And also attach the xmi file.

**Comment by pr0t3us** [comment]
@CarlKlagba Message:
The field 'name' does not possess any type, exiting now.
Error
    at Object.<anonymous> (C:\Users\...\npm\node_modules\jhipster-uml\lib\editors\modelio_parser.js:357:29)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\...\npm\node_modules\jhipster-uml\lib\editors\editors.js:3:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
and xmi file: https://gist.github.com/pr0t3us/82b5a8f6f326203abf29
I think it will be nice for some example uml/xmi files to be included in jhipster-uml tutorial so we can compare those files.

**Comment by CarlKlagba** [comment]
You did not use the elements "Attribute" to make your fields.
It seems like you used an association of some sort, that isn't correct.
Remake your classes with the elements 'Attribute' (just below the 'Class' one).

See here the xmi I generate : https://gist.github.com/CarlKlagba/adafec81265abc04b1e4#file-gistfile1-xml

**Comment by CarlKlagba** [comment]
And also the type float isn't supported by JHipster, create the datatype 'BigDecimal' to use instead of it.
See the annexe on our wiki to know more about the types you can use and those you have to define.
http://jhipster.github.io/jhipster_uml.html#annexes
