### ISSUE TITLE
unhandled 'error' event : cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by Noside93** [jhipster/jhipster-uml#90]
Hi,

I get an error with jhipster uml when I try to parse my diagram. I created a simple class diagram with only one class and two attribute (Integer and String)  and when I use the command : 

jhipster-uml myfile.uml

this error is thrown : 

Found the .jhipster/UMLTest.json configuration file, automatically generating the entity
The entity UMLTest is being created.
events.js:141
      throw er; // Unhandled 'error' event
      ^
	  
TypeError: C:\Users\noside\AppData\Roaming\npm\node_modules\generator-jhipster\
entity\templates\src\test\java\package\web\rest\_EntityResourceTest.java:53
    51|
    52|     private static final DateTimeFormatter dateTimeFormatter = DateTimeFormat.forPattern("yyyy-MM-dd'T'HH:mm:ss'Z'");<% } %>
 >> 53| <% for (fieldId in fields) {
    54|     var defaultValueName = 'DEFAULT_' + fields[fieldId].fieldNameUnderscored.toUpperCase();
    55|     var updatedValueName = 'UPDATED_' + fields[fieldId].fieldNameUnderscored.toUpperCase();
    56|

Cannot read property 'toUpperCase' of undefined
    at eval (eval at <anonymous> (C:\Users\noside\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\ejs\lib\ejs.js:455:12), <anonymous>:100:77)
    at C:\Users\noside\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\ejs\lib\ejs.js:482:14
    at Object.exports.render (C:\Users\noside\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\ejs\lib\ejs.js:316:13)
    at copy.process (C:\Users\noside\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\mem-fs-editor\actions\copy-tpl.js:14:18)
    at applyProcessingFunc (C:\Users\noside\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\mem-fs-editor\actions\copy.js:13:16)
    at EditionInterface.exports._copySingle (C:\Users\noside\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\mem-fs-editor\actions\copy.js:51:16)
    at EditionInterface.exports.copy (C:\Users\noside\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\mem-fs-editor\actions\copy.js:23:17)
    at EditionInterface.module.exports [as copyTpl] (C:\Users\noside\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\mem-fs-editor\actions\copy-tpl.js:12:8)
    at EntityGenerator.template (C:\Users\noside\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\actions\actions.js:134:11)
    at EntityGenerator.files (C:\Users\noside\AppData\Roaming\npm\node_modules\generator-jhipster\entity\index.js:876:10)

I tried with UML Designer and GenMyModel (with XMI export) but i always get the same issue

FYI : The version of my jHipster is v2.16.0, I installed this version to work with java 7.

Thank you for your help,

Noside

**Comment by MathieuAA** [comment]
Hello, can you post a pic of your diagram or at least copy/paste your XMI? I think you may have an error in your diagram.

**Comment by Noside93** [comment]
![test](https://cloud.githubusercontent.com/assets/16237830/11717429/b3c5a320-9f50-11e5-8add-8040fe715eaa.png)

XMI : 

<?xml version="1.0" encoding="UTF-8"?>
<uml:Model xmi:version="20131001" xmlns:xmi="http://www.omg.org/spec/XMI/20131001" xmlns:uml="http://www.eclipse.org/uml2/5.0.0/UML" xmi:id="_K9CMIJ8XEeWzicw_Cnjtpg" name="NewModel">
  <packagedElement xmi:type="uml:Class" xmi:id="_SXw4UJ8XEeWzicw_Cnjtpg" name="TestUML">
    <ownedAttribute xmi:id="_n0-nAJ9HEeWDOo1upGK_ZA" name="idTest" visibility="private">
      <type xmi:type="uml:PrimitiveType" href="pathmap://UML_LIBRARIES/UMLPrimitiveTypes.library.uml#Integer"/>
    </ownedAttribute>
    <ownedAttribute xmi:id="_W68IkJ8XEeWzicw_Cnjtpg" name="label" visibility="private">
      <type xmi:type="uml:PrimitiveType" href="pathmap://UML_LIBRARIES/UMLPrimitiveTypes.library.uml#String"/>
    </ownedAttribute>
  </packagedElement>
</uml:Model>

**Comment by MathieuAA** [comment]
Seems ok to me. Can you copy/paste TestUML.json from the .jhipster folder please?

**Comment by Noside93** [comment]
{
  "relationships": [],
  "fields": [
    {
      "fieldId": 1,
      "fieldName": "idTest",
      "fieldType": "Integer"
    },
    {
      "fieldId": 2,
      "fieldName": "label",
      "fieldType": "String"
    }
  ],
  "changelogDate": "20151210143708",
  "dto": "no",
  "pagination": "no"
}

**Comment by MathieuAA** [comment]
I don't see any error (except a tiny one about the id, but I highly doubt it can cause that). Try updating JHipster (generator-jhipster) and JHpster_UML to the latest version.

**Comment by Noside93** [comment]
I can't update jHipster because I want to work with Java 7, I think I will have to create my entities manually.

Thanks for your support 

Regards,

Noside

**Comment by MathieuAA** [comment]
You could do that, or downgrade the version of JHipster-UML v1.2.1 (warning, there were some bugs back in the day).
