### ISSUE TITLE
jhipster-uml mission module /lib/helper/jhipster_option_helper

### ISSUE THREAD

**Issue by fmatuszewski** [jhipster/jhipster-uml#92]
when: I execute from terminal  jhipster-uml model.jh 

then: I get an exception.
module.js:339
Error: Cannot find module './lib/helper/jhipster_option_helper'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/lib/node_modules/jhipster-uml/jhipster-uml.js:16:28)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)

Solution:
I see that ./lib/helper/jhipster_option_helper path is invalid
valid path is ./lib/helpers/jhipster_option_helper

**Comment by MathieuAA** [comment]
Hi, nice catch! Can you make a PR?

**Comment by fmatuszewski** [comment]
If you tell me where is this file module.js I can create a fix. but I am new to this plugin.

**Comment by MathieuAA** [comment]
The stacktrace is a bit ugly, I admit. Apparently, the problem seems to come from /jhipster-uml/jhipster-uml.js:16:28.

**Comment by MathieuAA** [comment]
I made a mistake in the commit, it is fixed as of 08605bf.
